<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Заточка режущего инструмента");
?><p></p><p class="" style="text-align: center;"><b><u><span style="color: #ed008c;">Уникальная технология заточки пил</span></u></b></p><p class="" style="text-align: justify;">Секрет нашей технологии заключается в нескольких составляющих: особых заточных камней различной зернистости, варьируемой скорости подачи камня, и, самое главное, в дополнительном шлифовании обеих сторон зубьев пилы после заточки. Такое дополнительное шлифование позволяет <b>максимально возможно увеличить ресурс пильного диска между переточками</b>. Т.к. за счет такого шлифования две стороны сводятся в исключительно тонкую линию режущей кромки. Толщина этой кромки настолько мала, что сопоставима с размерами самих зерен твердого сплава, из которого изготовлен зуб пильного диска.</p><p class="" style="text-align: justify;">Таким образом достигается преимущество по эксплуатации пильного диска на первоначальной стадии, когда она включается в работу гораздо более острая, чем её аналоги, заточенные "стандартным" способом на станке с ЧПУ. <b><span style="color: #f16522;">По отзывам наших партнеров-производственников общий ресурс пилы увеличивается примерно в 2-2,5 раза. Это напрямую означает, что и приобретать новые пилы вы будете в 2-2,5 раза реже.</span></b></p><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;">
 <tbody><tr style="height: 12.75pt;">
  <td colspan="2" width="653" style="width: 489.8pt; border: 1pt solid windowtext; height: 12.75pt; background-image: initial; background-color: #99ccff;">
  <p align="center"><b><u>Заточка алмазного
  инструмента&nbsp;</u></b></p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt;">
  <p align="center">Прямолинейные режущие грани, за 1
  погонный мм.</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt;">
  <p align="center">50,00 руб.&nbsp;</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">Профильные режущие грани, за 1
  погонный мм.</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">56,00 руб.&nbsp;</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt;">
  <p align="center">Торцевой алмазный зуб, за 1
  погонный мм.</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt;">
  <p align="center">50,00
  руб.&nbsp;</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">Торцевой твердосплавный зуб</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">бесплатно&nbsp;</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt;">
  <p align="center">Режущие грани дисковой пилы, за 1
  погон.мм.</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt;">
  <p align="center">50,00 руб.</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">Надбавка за съем более 0,3 мм.</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">надбавки нет</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt;">
  <p align="center">Восстановление (замена) режущих
  элементов за 1 кв.мм.</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt;">
  <p align="center">50,00 руб.&nbsp;</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">Балансировка инструмента</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center">входит в стоимость заточки&nbsp;</p>
  </td>
 </tr>
 <tr style="height: 12.75pt;">
  <td width="436" style="width: 326.8pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; height: 12.75pt;">
  <p align="center">Паспорт изменённого диаметра</p>
  </td>
  <td width="217" style="width: 163pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt;">
  <p align="center">прилагается бесплатно</p>
  </td>
 </tr>
</tbody></table><p></p><p></p><br><br><br>2<br><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td colspan="2" width="653" style="border: 1pt solid windowtext; width: 489.8pt; height: 12.75pt; background-image: initial; background-color: #99ccff;"><p align="center"><a href="http://btools.ru/upload/saw_sharpening.pdf" target="_blank"><b><span style="color: windowtext;">Заточка Пильных дисков</span></b></a><b><u>*</u></b><br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Основная
пила&nbsp;Z=96 форма зуба&nbsp;FZ/TR<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center">632,00р.</p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">Подрезная
пила&nbsp;Z=12+12 форма зуба&nbsp;WZ<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">227,00р.&nbsp;</p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center"><a href="http://btools.ru/bitrix/admin/fileman_file_download.php?path=%2Fupload%2Fmedialibrary%2F475%2F4754b4822a088a761378cf74c09f6344.jpg"><b>* -&nbsp;</b></a><a href="http://btools.ru/upload/saw_sharpening.pdf" target="_blank"></a><a href="http://btools.ru/bitrix/admin/fileman_file_download.php?path=%2Fupload%2Fmedialibrary%2F475%2F4754b4822a088a761378cf74c09f6344.jpg"><b>полный
прейскурант на заточку пил</b></a><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center"><a href="http://btools.ru/bitrix/admin/fileman_file_download.php?path=%2Fupload%2Fmedialibrary%2F475%2F4754b4822a088a761378cf74c09f6344.jpg"><b>скачать</b></a></p></td></tr></tbody></table>3<br><p></p><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td colspan="2" width="653" style="border: 1pt solid windowtext; width: 489.8pt; height: 12.75pt; background-image: initial; background-color: #99ccff;"><p align="center"><b><u>Заточка
строгальных ножей&nbsp;</u></b><br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Ножи из
быстрорежущей стали (HSS)<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><table cellspacing="0" cellpadding="0" align="left" width="552" style="width: 414.15pt; border-collapse: collapse;">
 <tbody><tr style="height: 12.75pt;">
  <td width="93" style="width: 69.85pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;">
  <p align="center"><b>L до 2</b><b>00мм</b></p></td><td width="115" style="width: 86.05pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><b><p>L более 200мм</p></b></td></tr><tr style="height: 12.75pt;"><td width="93" style="width: 69.85pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: white;"><p>100,00р.</p></td><td width="115" style="width: 86.05pt; border-top-width: initial; border-top-color: initial; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-style: solid; border-right-color: windowtext; border-right-width: 1pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">100р.+6р.за
каждые 10мм<br></p>
  </td>
 </tr>
</tbody></table></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">Ножи из
твердого сплава (HW)<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><table cellspacing="0" cellpadding="0" align="left" width="552" style="width: 414.15pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; background-image: initial;"><p align="center"><b>L до 2</b><b>00мм</b><br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; background-image: initial;"><p align="center"><b>L более 200мм</b></p></td></tr><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">100,00р.</p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">125р.+7р.за
каждые 10мм<br></p></td></tr></tbody></table></td></tr></tbody></table>4<br><br><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td colspan="2" width="653" style="border: 1pt solid windowtext; width: 489.8pt; height: 12.75pt; background-image: initial; background-color: #99ccff;"><p align="center"><b><u>Заточка
фрез&nbsp;</u></b><br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Фрезы
концевые по перед. грани, B до 30мм, за 1зуб<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center">84,00р.<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">Фрезы
концевые по перед. грани, B от 30мм, за 1зуб<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">168,00р.<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Фрезы
насадные по перед. грани, B до 20мм, за 1зуб<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center">84,00р.<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">Фрезы
насадные по перед. грани, В до 50мм, за 1зуб<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">168,00р.<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Фрезы
насадные по перед. грани, В от 50мм, за 1зуб<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center">252,00р.<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">Фрезы
насадные по задней. грани, за 1зуб<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">42,00р<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center"></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><br></td></tr></tbody></table>5<br><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td colspan="2" width="653" style="border: 1pt solid windowtext; width: 489.8pt; height: 12.75pt; background-image: initial; background-color: #99ccff;"><p align="center"><b><u>Заточка
свёрл&nbsp;</u></b><br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Сверла
для сквозных отверстий<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center">150,00р.&nbsp;<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">Сверла
для глухих отверстий<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center">173,00р.&nbsp;<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center">Сверла
чашечные<br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center">288,00р.<br></p></td></tr></tbody></table>6<p style="text-align: center;"></p><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td colspan="2" width="653" style="border: 1pt solid windowtext; width: 489.8pt; height: 12.75pt; background-image: initial; background-color: #99ccff;"><p align="center"><b><u>Заточка строгальных ножей&nbsp;</u></b><br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center" class="" style="text-align: center;"><b>Высота
режущей части&nbsp;h&nbsp;до 30 мм</b><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><table cellspacing="0" cellpadding="0" align="left" width="552" style="width: 414.15pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; text-align: center; background-image: initial; background-color: #e6e6e6;"><p align="center"><b>Z=2</b><br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; text-align: center; background-image: initial; background-color: #e6e6e6;"><b><p><b>Z=3</b><br></p></b></td></tr><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; background-image: initial; background-color: white;"><p class="" style="text-align: center;">377,00р.<br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">492,00р.<br></p></td></tr></tbody></table></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center" style="text-align: center;"><b>Высота режущей части&nbsp;h&nbsp;</b>о<b>т 30 мм
до 50 мм</b><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><table cellspacing="0" cellpadding="0" align="left" width="552" style="width: 414.15pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; text-align: center; background-image: initial;"><p align="center"><b>Z=2</b><br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; text-align: center; background-image: initial;"><p align="center"></p><p><b>Z=3</b></p></td></tr><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">397,00р<br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">518,00р.<br></p></td></tr></tbody></table></td></tr></tbody></table><br><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center" class="" style="text-align: center;"><b>Высота режущей части&nbsp;h&nbsp;от 50 мм
и выше</b><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><table cellspacing="0" cellpadding="0" align="left" width="552" style="width: 414.15pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; text-align: center; background-image: initial;"><p align="center"><b>Z=2</b><br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; text-align: center; background-image: initial;"><p align="center"></p><p><b>Z=3</b></p></td></tr><tr style="height: 12.75pt;"><td width="93" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 69.85pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">437,00р<br></p></td><td width="115" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 86.05pt; height: 12.75pt; background-image: initial; background-color: white;"><p align="center">569,00р.<br></p></td></tr></tbody></table></td></tr></tbody></table>7<br><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody><tr style="height: 12.75pt;"><td colspan="2" width="653" style="border: 1pt solid windowtext; width: 489.8pt; height: 12.75pt; background-image: initial; background-color: #99ccff;"><p align="center"><b>Дополнительные
условия:</b><br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center"><b>Минимальная
стоимость одного заказа&nbsp;</b><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center"><b>2000
руб.&nbsp; Цены указаны с учётом НДС.</b>.&nbsp;<br></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center"><b>Срок исполнения заказа&nbsp;</b><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt; background-image: initial; background-color: #e6e6e6;"><p align="center"></p><p align="center" style="text-align: center;"><b><span style="font-size: 10pt;">по т.с. — 7 рабочих дней, спиральному&nbsp;</span></b></p><p align="center" style="text-align: center;"><b><span style="font-size: 10pt;">т.с. - 10 рабочих дней,&nbsp;</span></b><br></p><p style="text-align: center;"><b><span style="font-size: 10pt;">
</span></b><span style="font-size: 10pt;"><b>по алмазу — 14 рабочих дней.</b></span></p></td></tr><tr style="height: 12.75pt;"><td width="436" style="border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 326.8pt; height: 12.75pt;"><p align="center"><b>Принятый
в заточку инструмент отправляется в работу&nbsp;</b><br></p></td><td width="217" style="border-top-width: initial; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: initial; border-right-style: solid; border-bottom-style: solid; border-top-color: initial; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: initial; width: 163pt; height: 12.75pt;"><p align="center"><b>без предварительного согласования.</b><br></p></td></tr></tbody></table><p style="text-align: center;"><br></p><p style="text-align: center;"><b><br></b></p><p style="text-align: center;"><b><br><br></b></p><p><br></p>
<p style="text-align: center;"><b><span style="color: #ff00ff;">Сервисный центр Биржи Технологий также осуществляет ремонт пильных дисков. Восстановление зубьев выполняется на первоклассном немецком оборудовании фирмы Vollmer при использовании только высококачественных немецких припоев. Твердый сплав производства Ceratizit.</span></b></p><p style="text-align: center;"><b><span style="font-size: 12pt;"><a href="http://www.btools.ru"><span style="font-size: 13pt;">Перейти в Каталог</span></a></span></b></p><table cellspacing="0" cellpadding="0" align="left" width="653" style="width: 489.8pt; border-collapse: collapse;"><tbody></tbody></table><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>